### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Krutoy242** [ukmojb/CustomFishing#3]
Starting server with Custom Fishing crash on load:

```ruby
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from customfishing (customfishing)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.getDeclaredConstructor(Class.java:2178)
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:326)
    at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findConstructor(ObfuscationReflectionHelper.java:194)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:297)
    at net.minecraftforge.fml.common.registry.EntityRegistry$EntityRegistration$1.<init>(EntityRegistry.java:81)
    at net.minecraftforge.fml.common.registry.EntityRegistry$EntityRegistration.<init>(EntityRegistry.java:80)
    at net.minecraftforge.fml.common.registry.EntityRegistry$EntityRegistration.<init>(EntityRegistry.java:67)
    at net.minecraftforge.fml.common.registry.EntityRegistry.doModEntityRegistration(EntityRegistry.java:199)
    at net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(EntityRegistry.java:173)
    at com.wdcftgg.customfishing.proxy.CommonProxy.onPreInit(CommonProxy.java:22)
    at com.wdcftgg.customfishing.CustomFishing.preInit(CustomFishing.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
[crash-2024-09-27_08.07.12-server.txt](https://github.com/user-attachments/files/17161124/crash-2024-09-27_08.07.12-server.txt)

**Comment by ukmojb** [comment]
Does 0.0.9 still have this problem?

**Comment by Krutoy242** [comment]
Will test it later.

**Comment by Krutoy242** [comment]
Ok, seems like server isn't crashing anymore.
